// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load`, `save`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<FeaturedContentInfo>> featuredContent(
        {required String source, required bool fromCache}) =>
    RustLib.instance.api
        .crateMethodMetadataProviderFeaturedContentFeaturedContent(
            source: source, fromCache: fromCache);

class FeaturedContentInfo {
  final String source;
  final String id;
  final String title;
  final List<String> contextual;
  final String shortDescription;
  final String bannerUrl;

  const FeaturedContentInfo({
    required this.source,
    required this.id,
    required this.title,
    required this.contextual,
    required this.shortDescription,
    required this.bannerUrl,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      id.hashCode ^
      title.hashCode ^
      contextual.hashCode ^
      shortDescription.hashCode ^
      bannerUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeaturedContentInfo &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          id == other.id &&
          title == other.title &&
          contextual == other.contextual &&
          shortDescription == other.shortDescription &&
          bannerUrl == other.bannerUrl;
}
