// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<TrendingContentInfo>> trendingContent(
        {required String source, required bool fromCache}) =>
    RustLib.instance.api
        .crateMethodMetadataProviderTrendingContentTrendingContent(
            source: source, fromCache: fromCache);

class TrendingContentInfo {
  final String source;
  final String id;
  final String title;
  final String year;
  final double rating;
  final String thumbnailUrl;

  const TrendingContentInfo({
    required this.source,
    required this.id,
    required this.title,
    required this.year,
    required this.rating,
    required this.thumbnailUrl,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      id.hashCode ^
      title.hashCode ^
      year.hashCode ^
      rating.hashCode ^
      thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrendingContentInfo &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          id == other.id &&
          title == other.title &&
          year == other.year &&
          rating == other.rating &&
          thumbnailUrl == other.thumbnailUrl;
}
