// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_cache_dir`, `load_cache`, `save_cache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

class EpisodeInfo {
  final String source;
  final String title;
  final String thumbnailUrl;

  const EpisodeInfo({
    required this.source,
    required this.title,
    required this.thumbnailUrl,
  });

  @override
  int get hashCode => source.hashCode ^ title.hashCode ^ thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpisodeInfo &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          title == other.title &&
          thumbnailUrl == other.thumbnailUrl;
}

class ExternalID {
  final String? mal;
  final String? kitsu;
  final String? imdb;

  const ExternalID({
    this.mal,
    this.kitsu,
    this.imdb,
  });

  static Future<ExternalID> default_() => RustLib.instance.api
      .crateMethodMetadataProviderViewContentExternalIdDefault();

  @override
  int get hashCode => mal.hashCode ^ kitsu.hashCode ^ imdb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExternalID &&
          runtimeType == other.runtimeType &&
          mal == other.mal &&
          kitsu == other.kitsu &&
          imdb == other.imdb;
}

class ViewContentInfo {
  final String source;
  final ExternalID externalId;
  final String url;
  final String title;
  final String titleSecondary;
  final String thumbnailUrl;
  final String bannerUrl;
  final List<String> contextual;
  final String description;
  final String trailerUrl;
  final PlatformInt64 countdown;
  final List<String> pictures;
  final List<List<EpisodeInfo>> episodes;
  final BigInt? lastWatchSeasonIndex;
  final BigInt? lastWatchEpisodeIndex;
  final String? lastUpdate;

  const ViewContentInfo({
    required this.source,
    required this.externalId,
    required this.url,
    required this.title,
    required this.titleSecondary,
    required this.thumbnailUrl,
    required this.bannerUrl,
    required this.contextual,
    required this.description,
    required this.trailerUrl,
    required this.countdown,
    required this.pictures,
    required this.episodes,
    this.lastWatchSeasonIndex,
    this.lastWatchEpisodeIndex,
    this.lastUpdate,
  });

  static Future<ViewContentInfo> get_(
          {required String source,
          required String id,
          required bool fromCache,
          required bool checkExpire}) =>
      RustLib.instance.api
          .crateMethodMetadataProviderViewContentViewContentInfoGet(
              source: source,
              id: id,
              fromCache: fromCache,
              checkExpire: checkExpire);

  static Future<void> updateLastWatch(
          {required String source,
          required String id,
          required BigInt seasonIndex,
          required BigInt episodeIndex}) =>
      RustLib.instance.api
          .crateMethodMetadataProviderViewContentViewContentInfoUpdateLastWatch(
              source: source,
              id: id,
              seasonIndex: seasonIndex,
              episodeIndex: episodeIndex);

  @override
  int get hashCode =>
      source.hashCode ^
      externalId.hashCode ^
      url.hashCode ^
      title.hashCode ^
      titleSecondary.hashCode ^
      thumbnailUrl.hashCode ^
      bannerUrl.hashCode ^
      contextual.hashCode ^
      description.hashCode ^
      trailerUrl.hashCode ^
      countdown.hashCode ^
      pictures.hashCode ^
      episodes.hashCode ^
      lastWatchSeasonIndex.hashCode ^
      lastWatchEpisodeIndex.hashCode ^
      lastUpdate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ViewContentInfo &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          externalId == other.externalId &&
          url == other.url &&
          title == other.title &&
          titleSecondary == other.titleSecondary &&
          thumbnailUrl == other.thumbnailUrl &&
          bannerUrl == other.bannerUrl &&
          contextual == other.contextual &&
          description == other.description &&
          trailerUrl == other.trailerUrl &&
          countdown == other.countdown &&
          pictures == other.pictures &&
          episodes == other.episodes &&
          lastWatchSeasonIndex == other.lastWatchSeasonIndex &&
          lastWatchEpisodeIndex == other.lastWatchEpisodeIndex &&
          lastUpdate == other.lastUpdate;
}
