// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<ChapterData>> getChapters(
        {required String imdbId, required String source}) =>
    RustLib.instance.api.crateMethodSubtitleProviderGetChaptersGetChapters(
        imdbId: imdbId, source: source);

class ChapterData {
  final String title;
  final String link;

  const ChapterData({
    required this.title,
    required this.link,
  });

  @override
  int get hashCode => title.hashCode ^ link.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterData &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          link == other.link;
}
