// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<GetAllInstalledSubtitlesData>> getAllInstalledSubtitles() => RustLib
    .instance.api
    .crateMethodSubtitleProviderGetAllInstalledSubtitlesGetAllInstalledSubtitles();

class GetAllInstalledSubtitlesData {
  final String source;
  final String id;
  final BigInt subtitleId;
  final String title;
  final String path;

  const GetAllInstalledSubtitlesData({
    required this.source,
    required this.id,
    required this.subtitleId,
    required this.title,
    required this.path,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      id.hashCode ^
      subtitleId.hashCode ^
      title.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetAllInstalledSubtitlesData &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          id == other.id &&
          subtitleId == other.subtitleId &&
          title == other.title &&
          path == other.path;
}
