// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Map<BigInt, GetInstalledSubtitlesData>> getInstalledSubtitles(
        {required String source,
        required String id,
        required BigInt seasonIndex,
        required BigInt episodeIndex}) =>
    RustLib.instance.api
        .crateMethodSubtitleProviderGetInstalledSubtitlesGetInstalledSubtitles(
            source: source,
            id: id,
            seasonIndex: seasonIndex,
            episodeIndex: episodeIndex);

class GetInstalledSubtitlesData {
  final String title;
  final String path;

  const GetInstalledSubtitlesData({
    required this.title,
    required this.path,
  });

  @override
  int get hashCode => title.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GetInstalledSubtitlesData &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          path == other.path;
}
