// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Map<String, List<SubtitleData>>> getSubtitles({required String link}) =>
    RustLib.instance.api
        .crateMethodSubtitleProviderGetSubtitlesGetSubtitles(link: link);

class SubtitleData {
  final String title;
  final String link;

  const SubtitleData({
    required this.title,
    required this.link,
  });

  @override
  int get hashCode => title.hashCode ^ link.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubtitleData &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          link == other.link;
}
