// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

Future<TorrentMetadata> getTorrentMetadata({required String torrentSource}) =>
    RustLib.instance.api
        .crateMethodTorrentProviderGetTorrentMetadataGetTorrentMetadata(
            torrentSource: torrentSource);

class FileInfo {
  final BigInt id;
  final String? path;
  final BigInt? length;
  final String? sha1;

  const FileInfo({
    required this.id,
    this.path,
    this.length,
    this.sha1,
  });

  @override
  int get hashCode =>
      id.hashCode ^ path.hashCode ^ length.hashCode ^ sha1.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          length == other.length &&
          sha1 == other.sha1;
}

class TorrentMetadata {
  final String? name;
  final BigInt? length;
  final List<FileInfo> files;

  const TorrentMetadata({
    this.name,
    this.length,
    required this.files,
  });

  @override
  int get hashCode => name.hashCode ^ length.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TorrentMetadata &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          length == other.length &&
          files == other.files;
}
