// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'get_installed_plugins.freezed.dart';
part 'get_installed_plugins.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<Map<String, InstalledPluginInfo>> getInstalledPlugins(
        {required String source}) =>
    RustLib.instance.api
        .crateMethodPluginProviderGetInstalledPluginsGetInstalledPlugins(
            source: source);

@freezed
sealed class InstalledPluginInfo with _$InstalledPluginInfo {
  const factory InstalledPluginInfo({
    required String hashedManifestRepoId,
    required String manifestRepoName,
    required String pluginName,
    required String pluginRepoUrl,
    required String pluginIconUrl,
    required String pluginPath,
    required String pluginVersion,
  }) = _InstalledPluginInfo;

  factory InstalledPluginInfo.fromJson(Map<String, dynamic> json) =>
      _$InstalledPluginInfoFromJson(json);
}
