// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<Map<String, InstalledPluginInfo>> getInstalledPlugins(
        {required String source}) =>
    RustLib.instance.api
        .crateMethodPluginProviderGetInstalledPluginsGetInstalledPlugins(
            source: source);

class InstalledPluginInfo {
  final String hashedManifestRepoId;
  final String manifestRepoName;
  final String pluginName;
  final String pluginRepoUrl;
  final String pluginIconUrl;
  final String pluginPath;
  final String pluginVersion;

  const InstalledPluginInfo({
    required this.hashedManifestRepoId,
    required this.manifestRepoName,
    required this.pluginName,
    required this.pluginRepoUrl,
    required this.pluginIconUrl,
    required this.pluginPath,
    required this.pluginVersion,
  });

  @override
  int get hashCode =>
      hashedManifestRepoId.hashCode ^
      manifestRepoName.hashCode ^
      pluginName.hashCode ^
      pluginRepoUrl.hashCode ^
      pluginIconUrl.hashCode ^
      pluginPath.hashCode ^
      pluginVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstalledPluginInfo &&
          runtimeType == other.runtimeType &&
          hashedManifestRepoId == other.hashedManifestRepoId &&
          manifestRepoName == other.manifestRepoName &&
          pluginName == other.pluginName &&
          pluginRepoUrl == other.pluginRepoUrl &&
          pluginIconUrl == other.pluginIconUrl &&
          pluginPath == other.pluginPath &&
          pluginVersion == other.pluginVersion;
}
