// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'settings.freezed.dart';
part 'settings.g.dart';

@freezed
sealed class Paths with _$Paths {
  const factory Paths({
    required String appSupportDir,
    required String appCacheDir,
    required String tempDir,
  }) = _Paths;

  factory Paths.fromJson(Map<String, dynamic> json) => _$PathsFromJson(json);
}

@freezed
sealed class Settings with _$Settings {
  const factory Settings({
    required int port,
    required Paths paths,
  }) = _Settings;

  factory Settings.fromJson(Map<String, dynamic> json) =>
      _$SettingsFromJson(json);
}
