// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Paths {
  final String appSupportDir;
  final String appCacheDir;
  final String tempDir;

  const Paths({
    required this.appSupportDir,
    required this.appCacheDir,
    required this.tempDir,
  });

  @override
  int get hashCode =>
      appSupportDir.hashCode ^ appCacheDir.hashCode ^ tempDir.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Paths &&
          runtimeType == other.runtimeType &&
          appSupportDir == other.appSupportDir &&
          appCacheDir == other.appCacheDir &&
          tempDir == other.tempDir;
}

class Settings {
  final int port;
  final Paths paths;
  final String version;

  const Settings({
    required this.port,
    required this.paths,
    required this.version,
  });

  @override
  int get hashCode => port.hashCode ^ paths.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          port == other.port &&
          paths == other.paths &&
          version == other.version;
}
