// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

class CheckUpdate {
  final String latestVersion;
  final String downloadUrl;

  const CheckUpdate({
    required this.latestVersion,
    required this.downloadUrl,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<CheckUpdate?> newInstance() =>
      RustLib.instance.api.crateMethodCheckUpdateCheckUpdateNew();

  @override
  int get hashCode => latestVersion.hashCode ^ downloadUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckUpdate &&
          runtimeType == other.runtimeType &&
          latestVersion == other.latestVersion &&
          downloadUrl == other.downloadUrl;
}
