// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_remote`, `get_cache_path`, `load_cache`, `save_cache`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DirectStreamCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

class DirectStreamProvider {
  final String icon;
  final String title;
  final IdType idType;
  final UrlSchema urlSchema;
  final List<String> allowedNavigationOrigin;

  const DirectStreamProvider({
    required this.icon,
    required this.title,
    required this.idType,
    required this.urlSchema,
    required this.allowedNavigationOrigin,
  });

  static Future<DirectStreamProvider> get_({required String id}) =>
      RustLib.instance.api
          .crateMethodDirectStreamProviderDirectStreamProviderGet(id: id);

  static Future<Map<String, DirectStreamProvider>> getAll(
          {required bool fromCache}) =>
      RustLib.instance.api
          .crateMethodDirectStreamProviderDirectStreamProviderGetAll(
              fromCache: fromCache);

  @override
  int get hashCode =>
      icon.hashCode ^
      title.hashCode ^
      idType.hashCode ^
      urlSchema.hashCode ^
      allowedNavigationOrigin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirectStreamProvider &&
          runtimeType == other.runtimeType &&
          icon == other.icon &&
          title == other.title &&
          idType == other.idType &&
          urlSchema == other.urlSchema &&
          allowedNavigationOrigin == other.allowedNavigationOrigin;
}

class IdType {
  final String? movies;
  final String? tv;
  final String? anime;

  const IdType({
    this.movies,
    this.tv,
    this.anime,
  });

  Future<String?> get_({required String s}) => RustLib.instance.api
      .crateMethodDirectStreamProviderIdTypeGet(that: this, s: s);

  @override
  int get hashCode => movies.hashCode ^ tv.hashCode ^ anime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdType &&
          runtimeType == other.runtimeType &&
          movies == other.movies &&
          tv == other.tv &&
          anime == other.anime;
}

class UrlSchema {
  final String? movies;
  final String? tv;
  final String? anime;

  const UrlSchema({
    this.movies,
    this.tv,
    this.anime,
  });

  Future<String?> get_({required String s}) => RustLib.instance.api
      .crateMethodDirectStreamProviderUrlSchemaGet(that: this, s: s);

  @override
  int get hashCode => movies.hashCode ^ tv.hashCode ^ anime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UrlSchema &&
          runtimeType == other.runtimeType &&
          movies == other.movies &&
          tv == other.tv &&
          anime == other.anime;
}
