// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'download_provider.freezed.dart';
part 'download_provider.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `hash`, `hash`

Future<ArcDatabase> getDb() =>
    RustLib.instance.api.crateMethodDownloadProviderGetDb();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Database >>>
abstract class ArcDatabase implements RustOpaqueInterface {}

class DownloadItemKey {
  final String source;
  final String id;
  final BigInt seasonIndex;
  final BigInt episodeIndex;

  const DownloadItemKey({
    required this.source,
    required this.id,
    required this.seasonIndex,
    required this.episodeIndex,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      id.hashCode ^
      seasonIndex.hashCode ^
      episodeIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadItemKey &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          id == other.id &&
          seasonIndex == other.seasonIndex &&
          episodeIndex == other.episodeIndex;
}

class DownloadItemValue {
  final String torrentSource;
  final BigInt fileId;
  final String filePath;
  final String mimeType;

  const DownloadItemValue({
    required this.torrentSource,
    required this.fileId,
    required this.filePath,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      torrentSource.hashCode ^
      fileId.hashCode ^
      filePath.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadItemValue &&
          runtimeType == other.runtimeType &&
          torrentSource == other.torrentSource &&
          fileId == other.fileId &&
          filePath == other.filePath &&
          mimeType == other.mimeType;
}

@freezed
sealed class DownloadStatus with _$DownloadStatus {
  const factory DownloadStatus({
    required BigInt progressSize,
    required BigInt totalSize,
    required bool paused,
    required bool done,
  }) = _DownloadStatus;

  factory DownloadStatus.fromJson(Map<String, dynamic> json) =>
      _$DownloadStatusFromJson(json);
}
