// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'download_provider.freezed.dart';
part 'download_provider.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `hash`, `hash`

Future<ArcDatabase> getDb() =>
    RustLib.instance.api.crateMethodDownloadProviderGetDb();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Database >>>
abstract class ArcDatabase implements RustOpaqueInterface {}

@freezed
sealed class DownloadItemKey with _$DownloadItemKey {
  const factory DownloadItemKey({
    required String source,
    required String id,
    required BigInt seasonIndex,
    required BigInt episodeIndex,
  }) = _DownloadItemKey;

  factory DownloadItemKey.fromJson(Map<String, dynamic> json) =>
      _$DownloadItemKeyFromJson(json);
}

@freezed
sealed class DownloadItemValue with _$DownloadItemValue {
  const factory DownloadItemValue({
    required String torrentSource,
    required BigInt fileId,
    required String filePath,
    required String mimeType,
  }) = _DownloadItemValue;

  factory DownloadItemValue.fromJson(Map<String, dynamic> json) =>
      _$DownloadItemValueFromJson(json);
}

@freezed
sealed class DownloadStatus with _$DownloadStatus {
  const factory DownloadStatus({
    required BigInt progressSize,
    required BigInt totalSize,
    required bool paused,
    required bool done,
  }) = _DownloadStatus;

  factory DownloadStatus.fromJson(Map<String, dynamic> json) =>
      _$DownloadStatusFromJson(json);
}
