// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'favorite.freezed.dart';
part 'favorite.g.dart';

Future<ArcDatabase> getDb() => RustLib.instance.api.crateMethodFavoriteGetDb();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Database >>>
abstract class ArcDatabase implements RustOpaqueInterface {}

@freezed
sealed class CategoryMap with _$CategoryMap {
  const factory CategoryMap({
    required Map<BigInt, String> field0,
  }) = _CategoryMap;

  factory CategoryMap.fromJson(Map<String, dynamic> json) =>
      _$CategoryMapFromJson(json);
}

@freezed
sealed class CategoryOrderMap with _$CategoryOrderMap {
  const factory CategoryOrderMap({
    required Map<BigInt, BigInt> field0,
  }) = _CategoryOrderMap;

  factory CategoryOrderMap.fromJson(Map<String, dynamic> json) =>
      _$CategoryOrderMapFromJson(json);
}

@freezed
sealed class ItemInfo with _$ItemInfo {
  const factory ItemInfo({
    required String source,
    required String id,
  }) = _ItemInfo;

  factory ItemInfo.fromJson(Map<String, dynamic> json) =>
      _$ItemInfoFromJson(json);
}
