// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'download_provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ArcDatabase> getDb() => RustLib.instance.api.crateMethodFavoriteGetDb();

class CategoryMap {
  final Map<BigInt, String> field0;

  const CategoryMap({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryMap &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class CategoryOrderMap {
  final Map<BigInt, BigInt> field0;

  const CategoryOrderMap({
    required this.field0,
  });

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CategoryOrderMap &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}

class FavoriteItemInfo {
  final String source;
  final String id;

  const FavoriteItemInfo({
    required this.source,
    required this.id,
  });

  @override
  int get hashCode => source.hashCode ^ id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FavoriteItemInfo &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          id == other.id;
}

class LastWatchTorrentInfo {
  final String torrentSource;
  final BigInt fileId;
  final String mimeType;

  const LastWatchTorrentInfo({
    required this.torrentSource,
    required this.fileId,
    required this.mimeType,
  });

  @override
  int get hashCode =>
      torrentSource.hashCode ^ fileId.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LastWatchTorrentInfo &&
          runtimeType == other.runtimeType &&
          torrentSource == other.torrentSource &&
          fileId == other.fileId &&
          mimeType == other.mimeType;
}
