// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class PluginInfo {
  final String hashedManifestRepoId;
  final String manifestRepoName;
  final String pluginId;
  final String pluginName;
  final String pluginRepoUrl;
  final String pluginIconUrl;

  const PluginInfo({
    required this.hashedManifestRepoId,
    required this.manifestRepoName,
    required this.pluginId,
    required this.pluginName,
    required this.pluginRepoUrl,
    required this.pluginIconUrl,
  });

  @override
  int get hashCode =>
      hashedManifestRepoId.hashCode ^
      manifestRepoName.hashCode ^
      pluginId.hashCode ^
      pluginName.hashCode ^
      pluginRepoUrl.hashCode ^
      pluginIconUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginInfo &&
          runtimeType == other.runtimeType &&
          hashedManifestRepoId == other.hashedManifestRepoId &&
          manifestRepoName == other.manifestRepoName &&
          pluginId == other.pluginId &&
          pluginName == other.pluginName &&
          pluginRepoUrl == other.pluginRepoUrl &&
          pluginIconUrl == other.pluginIconUrl;
}
