// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'download_provider.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ArcDatabase> getDb() =>
    RustLib.instance.api.crateMethodWatchStateGetDb();

class WatchStateKey {
  final String source;
  final String id;
  final BigInt seasonIndex;
  final BigInt episodeIndex;

  const WatchStateKey({
    required this.source,
    required this.id,
    required this.seasonIndex,
    required this.episodeIndex,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      id.hashCode ^
      seasonIndex.hashCode ^
      episodeIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatchStateKey &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          id == other.id &&
          seasonIndex == other.seasonIndex &&
          episodeIndex == other.episodeIndex;
}

class WatchStateValue {
  final BigInt? position;

  const WatchStateValue({
    this.position,
  });

  @override
  int get hashCode => position.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WatchStateValue &&
          runtimeType == other.runtimeType &&
          position == other.position;
}
